version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: "ubuntu-22.04"
  apt_packages:
    - llvm
  tools:
    python: "3.10"
  jobs:
    pre_install:
      - python -m pip install --upgrade pip wheel setuptools numpy GitPython sphinx sphinx-rtd-theme myst-parser
    pre_build:
      - rm -rf docs/source/generated
      - sphinx-apidoc
        --private
        --module-first
        --force
        --output-dir docs/source/generated
        pygama

python:
  install:
    - method: pip
      path: .
